#!/bin/bash

update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/paper-town/paper-town.plymouth 100
update-alternatives --install /usr/share/plymouth/themes/text.plymouth text.plymouth /usr/share/plymouth/themes/paper-town-text/paper-town-text.plymouth 100

update-initramfs -u
